# Generated by Django 4.1 on 2022-08-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_year_glass_costo_rename_title_glass_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glass',
            name='alto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glass',
            name='grosor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glass',
            name='largo',
            field=models.IntegerField(default=0),
        ),
    ]
