# Generated by Django 4.1 on 2022-08-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_glass_alto_glass_grosor_glass_largo'),
    ]

    operations = [
        migrations.AddField(
            model_name='glass',
            name='tipo',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
