# Generated by Django 4.1 on 2022-08-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_glass_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
