# Generated by Django 4.0.6 on 2022-08-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_glass_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='glass',
            name='imagen',
            field=models.ImageField(null=True, upload_to='vidrios'),
        ),
    ]
