# Generated by Django 4.0.6 on 2022-08-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_glass_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='glass',
            name='descripcion',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
